<?php
ob_start();
//error_reporting(0);

include 'conn.php';
//include 'session_handler.php';
require_once('tcpdf_include_a4l.php');
$curdte=date("Y-m-d");

$sql4="SELECT * FROM course_batch_details INNER JOIN course_master ON course_batch_details.course_key=course_master.coursemas_key
																			WHERE course_batch_details.course_batch_details_key='$_GET[bt]'
																			AND course_batch_details.finact=0";
$result4 = mysqli_query($link,$sql4);
while($row4=mysqli_fetch_array($result4)){
	$course_nme=$row4['course_nme'];
	$batch_nme=$row4['batch_nme'];
	
}


	class MYPDF extends TCPDF {

		//Page header
		public function Header() {
			
			include 'conn.php';
			//include 'session_handler.php';
			
			$sql4="SELECT * FROM course_batch_details INNER JOIN course_master ON course_batch_details.course_key=course_master.coursemas_key
																			WHERE course_batch_details.course_batch_details_key='$_GET[bt]'
																			AND course_batch_details.finact=0";
			$result4 = mysqli_query($link,$sql4);
			while($row4=mysqli_fetch_array($result4)){
				$course_nme=$row4['course_nme'];
				$batch_nme=$row4['batch_nme'];
				
			}

			$img_file1 = 'images/dtetlogo.jpg';
			$this->Image($img_file1, 18, 2, 20, 18, '', '', '', false, 300, '', false, false, 0);
			$img_file2 = 'images/logo.jpg';
			$this->Image($img_file2, 250, 0, 25, 25, '', '', '', false, 300, '', false, false, 0);
				// Render the image
			$this->SetFont('times', 'B', 20);
				
			$html ='<table border="0">
									<tr>
										<td width="100%"><h2 align="center" style="color:#001f4d;font-size:16px"> Department of Technical Education and Training </h2> </td>
									</tr>';
							$html.= '<tr>
										<td width="100%" style="color:#001f4d;font-size:15px"><h5 align="center"> Interview Shedule Report </h5> </td>
									</tr>';
									
							$html.= '<tr>
										<td width="100%" style="color:#001f4d;font-size:15px"><h5 align="center"> '.$course_nme.'   '.$batch_nme.'</h5> </td>
									</tr>';
							
			$html.='</table>
				<hr>';
			$this->writeHTML($html, true, false, true, false, '');
				// Title
		  
		}
		public function Footer() {
				include 'session_handler.php';
				
				$ftext='<hr>
					<table border="0" width="100%">
							<tr>
								<td width="20%">'.$ses_user.'</td>
								
								<td width="80%" align="right">Report Generated by DTET - Information System &nbsp;&nbsp;&nbsp; Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages().'</td>
							</tr>
							
					</table>';
			// Position at 15 mm from bottom
			$this->SetY(-8);
			// Set font
			$this->SetFont('times', 'I', 12);
			// Page number
			$this->writeHTML($ftext, true, false, true, false, '');
		}
	}
	
	
	// create new PDF document
	$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

	// set document information
	$pdf->SetCreator(PDF_CREATOR);

	$pdf->SetTitle('Interview Shedule Report');
	$pdf->SetSubject('TCPDF Tutorial');
	$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

	// set default header data
	// set header and footer fonts
	$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
	$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

	// set default monospaced font
	$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

	// set margins
	$pdf->SetMargins(PDF_MARGIN_LEFT, 24, PDF_MARGIN_RIGHT);
	$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
	$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

	// set auto page breaks
	$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

	// set image scale factor
	$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

	// set some language-dependent strings (optional)
	if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
		require_once(dirname(__FILE__).'/lang/eng.php');
		$pdf->setLanguageArray($l);
	}

	// ---------------------------------------------------------

	// set font
	$pdf->SetFont('times', '', 8);

	// add a page
	$pdf->AddPage();
		
	$html='<table border="1" width="100%">';
	$html.='<tbody>';
			$html.='<tr style="background-color:#3b4e87;color:#ffffff;font-size:12px">
					<td width="3%"> No</td>
					<td width="8%"> Name</td>
					<td width="8%" align="center">Address</td>
					<td width="4%" align="center">Telephone No</td>
					<td width="8%" align="center">NIC No</td>
					<td width="4%" align="center">Date of Birth</td>
					<td width="5%" align="center">Age</td>
					<td width="15%" align="center">O/L</td>
					<td width="15%" align="center">A/L</td>
					<td width="5%" align="center">GS certificate</td>
					<td width="5%" align="center">Charter Certificate</td>
					<td width="5%" align="center">Appitute Test marks</td>
					<td width="5%" align="center">other</td>
					<td width="5%" align="center">Marks</td>
					<td width="5%" align="center">selected or not</td>
				</tr>';	

            
            
			$n=0;
            $sql3="SELECT * FROM student_master INNER JOIN student_newselected_course_details ON student_master.studentmas_key=student_newselected_course_details.student_key
												WHERE student_newselected_course_details.coursebatch_detail_key='$_GET[bt]'
												 AND student_newselected_course_details.finact=0";
            $result3 = mysqli_query($link,$sql3);
            while($row3=mysqli_fetch_array($result3)){
				
				$n++;
				
				$d1 = new DateTime($curdte);
				$d2 = new DateTime($row3['date_of_birth']);

				$diff = $d2->diff($d1);

				$age=$diff->y;
               
                $html.='<tr style="font-size:12px">
					        <td width="3%"> '.$n.'</td>';
					$html.='<td width="8%"> '.$row3['student_nme'].'</td>';
					$html.='<td width="8%"> '.$row3['student_addr'].'</td>';
					$html.='<td width="4%"> '.$row3['tpnum'].'</td>';
					$html.='<td width="8%"> '.$row3['nic_no'].'</td>';
					$html.='<td width="4%"> '.$row3['date_of_birth'].'</td>';
					$html.='<td width="5%"> '.$age.'</td>';
					$html.='<td width="15%">';
						$sql5="SELECT * FROM student_qualification_details INNER JOIN examsubject_master ON student_qualification_details.examsubject_mas_key=examsubject_master.examsubjectmas_key
																		   INNER JOIN creditpoint_master ON student_qualification_details.creditpoint_key=creditpoint_master.creditpointmas_key
																		   INNER JOIN student_exam_details ON student_qualification_details.student_exam_details_key=student_exam_details.student_exam_key
																		   INNER JOIN exam_master ON student_exam_details.exam_key=exam_master.exammas_key
																		   WHERE student_qualification_details.student_key='$row3[studentmas_key]'
																		   AND exam_master.exam_name='G.C.E O/L'
																		   AND student_qualification_details.finact=0";
						 $result5 = mysqli_query($link,$sql5);
						while($row5=mysqli_fetch_array($result5)){
							$html.=''.$row5['stream'].' '.$row5['subject_name'].' - '.$row5['cedit_name'].'<br>';
						}
					$html.='</td>';
					$html.='<td width="15%">';
						$sql6="SELECT * FROM student_qualification_details INNER JOIN examsubject_master ON student_qualification_details.examsubject_mas_key=examsubject_master.examsubjectmas_key
																		   INNER JOIN creditpoint_master ON student_qualification_details.creditpoint_key=creditpoint_master.creditpointmas_key
																		   INNER JOIN student_exam_details ON student_qualification_details.student_exam_details_key=student_exam_details.student_exam_key
																		   INNER JOIN exam_master ON student_exam_details.exam_key=exam_master.exammas_key
																		   WHERE student_qualification_details.student_key='$row3[studentmas_key]'
																		   AND exam_master.exam_name='G.C.E. A/L'
																		   AND student_qualification_details.finact=0";
						 $result6 = mysqli_query($link,$sql6);
						while($row6=mysqli_fetch_array($result6)){
							$html.=''.$row6['stream'].' '.$row6['subject_name'].' - '.$row6['cedit_name'].'<br>';
						}
					$html.='</td>';
					$html.='<td width="5%"> </td>';
					$html.='<td width="5%"> </td>';
					$html.='<td width="5%"> </td>';
					$html.='<td width="5%"> </td>';
					$html.='<td width="5%"> </td>';
					$html.='<td width="5%"> </td>';
					
				$html.='</tr>';
				
				
            }
            
	$html.='</tbody>';
	$html.='</table>';
	
	
// Print text using writeHTMLCell()
$pdf->writeHTML($html, true, false, false, false, '');

// ---------------------------------------------------------

// Close and output PDF document
// This method has several options, check the source code documentation for more information.
$pdf->Output('Interviewshedulue_Report_'.$course_nme.'_'.$batch_nme.'_'.$curdte.'.pdf', 'I');


//============================================================+
// END OF FILE
//============================================================+