<?php
ob_start();
//error_reporting(0);

include 'conn.php';
//include 'session_handler.php';
require_once('tcpdf_include_a4l.php');
$curdte=date("Y-m-d");




	class MYPDF extends TCPDF {

		//Page header
		public function Header() {
			
			include 'conn.php';
			//include 'session_handler.php';
			
			

			$img_file1 = 'images/govlogo.png';
			$this->Image($img_file1, 155, 2, 5, 5, '', '', '', false, 300, '', false, false, 0);
			//$img_file2 = 'images/phdtlogo2.png';
			//$this->Image($img_file2, 40, 18, 60, 15, '', '', '', false, 300, '', false, false, 0);
				// Render the image
			$this->SetFont('times', 'B', 20);
				
			$html ='<table border="0">
									<tr>
										<td width="100%"><h2 align="center" style="color:#001f4d;font-size:16px"> Department of Technical Education and Training </h2> </td>
									</tr>';
							$html.= '<tr>
										<td width="100%" style="color:#001f4d;font-size:15px"><h5 align="center"> OJT Report </h5> </td>
									</tr>';
									
							$html.= '<tr>
										<td width="100%" style="color:#001f4d;font-size:15px"><h5 align="center"> '.$_GET['st'].' '.$_GET['ed'].'  </h5> </td>
									</tr>';
							
			$html.='</table>
				<hr>';
			$this->writeHTML($html, true, false, true, false, '');
				// Title
		  
		}
		public function Footer() {
				include 'session_handler.php';
				
				$ftext='<hr>
					<table border="0" width="100%">
							<tr>
								<td width="20%">'.$ses_user.'</td>
								
								<td width="80%" align="right">Report Generated by DTET - Information System &nbsp;&nbsp;&nbsp; Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages().'</td>
							</tr>
							
					</table>';
			// Position at 15 mm from bottom
			$this->SetY(-8);
			// Set font
			$this->SetFont('times', 'I', 12);
			// Page number
			$this->writeHTML($ftext, true, false, true, false, '');
		}
	}
	
	
	// create new PDF document
	$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

	// set document information
	$pdf->SetCreator(PDF_CREATOR);

	$pdf->SetTitle('Interview Shedule Report');
	$pdf->SetSubject('TCPDF Tutorial');
	$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

	// set default header data
	// set header and footer fonts
	$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
	$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

	// set default monospaced font
	$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

	// set margins
	$pdf->SetMargins(PDF_MARGIN_LEFT, 24, PDF_MARGIN_RIGHT);
	$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
	$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

	// set auto page breaks
	$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

	// set image scale factor
	$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

	// set some language-dependent strings (optional)
	if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
		require_once(dirname(__FILE__).'/lang/eng.php');
		$pdf->setLanguageArray($l);
	}

	// ---------------------------------------------------------

	// set font
	$pdf->SetFont('times', '', 8);

	// add a page
	$pdf->AddPage();
		
	$html='<table border="1" width="100%">';
	$html.='<tbody>';
			$html.='<tr style="background-color:#3b4e87;color:#ffffff;font-size:12px">
					<td width="5%"> No</td>
					<td width="18%"> Name</td>
					<td width="10%" align="center">Approve Date</td>
					<td width="12%" align="center">NIC No</td>
					<td width="15%" align="center">Course</td>
					<td width="10%" align="center">Batch</td>
					<td width="15%" align="center">Training Point</td>
					<td width="15%" align="center">Designation</td>

				</tr>';	

            
            
			$n=0;
            $sql3="SELECT * FROM student_trainingpoint_master INNER JOIN course_master ON student_trainingpoint_master.course_key=course_master.coursemas_key 
																					  INNER JOIN course_batch_details ON student_trainingpoint_master.coursebatch_detail_key=course_batch_details.course_batch_details_key
																					  INNER JOIN student_master ON student_trainingpoint_master.student_key=student_master.studentmas_key
																					  WHERE student_trainingpoint_master.approve_status=1
																						AND student_trainingpoint_master.finact=0 
																						AND course_batch_details.finact=0
																						AND course_master.finact=0
																						AND student_master.finact=0";
            $result3 = mysqli_query($link,$sql3);
            while($row3=mysqli_fetch_array($result3)){
				
				$n++;
				
				
               
                $html.='<tr style="font-size:12px">
					        <td width="5%"> '.$n.'</td>';
					$html.='<td width="18%"> '.$row3['student_nme'].'</td>';
					$html.='<td width="10%"> '.$row3['approve_dte'].'</td>';
					$html.='<td width="12%"> '.$row3['nic_no'].'</td>';
					$html.='<td width="15%"> '.$row3['course_nme'].'</td>';
					$html.='<td width="10%"> '.$row3['batch_nme'].'</td>';
					$html.='<td width="15%"> '.$row3['training_point_nme'].'</td>';
					$html.='<td width="15%"> '.$row3['training_point_designation'].'</td>';
					
					
				$html.='</tr>';
				
				
            }
            
	$html.='</tbody>';
	$html.='</table>';
	
	
// Print text using writeHTMLCell()
$pdf->writeHTML($html, true, false, false, false, '');

// ---------------------------------------------------------

// Close and output PDF document
// This method has several options, check the source code documentation for more information.
$pdf->Output('ojt_Report_'.$_GET['st'].'_'.$_GET['ed'].'.pdf', 'I');


//============================================================+
// END OF FILE
//============================================================+